package gobblets.ihm;

public enum Menu {
	MENU_FICHIER,
	MENU_OUVRIR,
	MENU_ENREGISTRER,
	MENU_NOUVEAU,
	MENU_QUITTER,
	MENU_AIDE,
	MENU_APROPOS,
	MENU_LANGUE, 
	MENU_TITRE_APROPOS, 
	MENU_TITRE_REGLES, MENU_TITRE_QUITTER, MENU_TITRE_SAUVEGARDER, MENU_TITRE_CHARGER, MENU_TITRE_ENG, MENU_TITRE_FR, MENU_TITRE_GER, MENU_TITRE_AIDE, MENU_TITRE_LANGUE, MENU_TITRE_NEW;
	
	Menu(){
		
	}
}
